apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-commander
  name: redis-commander
  namespace: {{ .namespace | default "default" }}
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: redis-commander
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: {{ .namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
        tier: backend
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:{{ .tag | default "latest" }}   
        env:
        - name: REDIS_HOSTS
          value: redis:{{ .redis_host | default "redis:6379" }}
        - name: REDIS_PORT
          value: ""
        ports:
        - name: redis-commander
          containerPort: 8081
        resources:
          limits:
            cpu: "100m"
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
{{ if .whr_host }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .namespace | default "default" }}
  annotations:
    kubernetes.io/ingress.class: webrelay # other ingress classes will be ignored
  name: redis-cmdr-ingress
spec:
  rules:
    - host: {{ .whr_host }}
      http:
        paths:        
        - path: /
          backend:
            serviceName: redis-commander
            servicePort: 8081
{{ end}}