apiVersion: v1
kind: Namespace
metadata:
  name: webrelay-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webrelay
  namespace: {{ .namespace | default "webrelay-ingress" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webrelay-credentials
  namespace: {{ .namespace | default "webrelay-ingress" }}
type: Opaque
data:
  key: {{ .key | b64enc }}
  secret: {{ .secret | b64enc }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webrelay
  name: webrelay
  namespace: {{ .namespace | default "webrelay-ingress" }}
spec:
  selector:
    matchLabels:
      app: webrelay
  replicas: 1
  template:
    metadata:
      labels:
        app: webrelay
    spec:
      containers:
      - image: docker.io/webrelay/ingress:{{ .tag | default "latest" }}
        imagePullPolicy: Always
        name: webrelay
        command: ["reingress"]
        args: ["server", "--incluster"]           
        env:
          - name: RELAY_KEY
            valueFrom:
              secretKeyRef:
                name: webrelay-credentials
                key: key
          - name: RELAY_SECRET
            valueFrom:
              secretKeyRef:
                name: webrelay-credentials
                key: secret
          - name: RELAY_NAME
            value: {{ .relay_name | default "default-cluster" }}
      dnsPolicy: ClusterFirst
      serviceAccountName: webrelay
      terminationGracePeriodSeconds: 10     
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: webrelay
  namespace: {{ .namespace | default "webrelay-ingress" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webrelay
subjects:
- kind: ServiceAccount
  name: webrelay
  namespace: webrelay-ingress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: webrelay
  namespace: {{ .namespace | default "webrelay-ingress" }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods  
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch